#---------------------------------------------------
#General Parameters 
#---------------------------------------------------
ALL: "ZTH115"
SAMPLES: "ZTH15samples.tsv"
ANNOTATIONFILE: "ZTH115annotations.txt" 
nCount1: 1200
nCount2: 30000
nfeatures1: 800
nfeatures2: 6000
mt: 25


